# Generated by Django 2.0.7 on 2018-08-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Nome'),
        ),
    ]
