# Generated by Django 2.0.7 on 2018-08-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0002_auto_20180827_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='stream',
            field=models.CharField(blank=True, choices=[('MANY_TO_MANY', 0), ('ONE_TO_MANY', 1)], default='None', max_length=10, null=True, verbose_name='Stream'),
        ),
    ]
