# Generated by Django 2.0.7 on 2018-08-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0006_auto_20180829_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', unique=True),
        ),
    ]
