# Generated by Django 2.0.7 on 2018-08-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0007_auto_20180829_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='grupo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
