# Generated by Django 2.0.7 on 2018-08-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0008_auto_20180829_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='grupo',
            new_name='pagina',
        ),
    ]
