# Generated by Django 2.0.7 on 2018-08-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0011_auto_20180829_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='pagina',
        ),
    ]
